### ISSUE TITLE
Add Test Cases management to project

### ISSUE THREAD

**Issue by MeIsBored** [Termiux/CO-Docs-Admin#9]
Test Cases support can be added as a feature once the original project is finished.

Properties:
* ID
* Name
* Description
* CO related
* Phase - Not sure about this one because we only add them for MO
* Estimated ITF date of CO can be used as a reference for deadline so it can send a reminder a few days before its due date

Status:
* Identified
* In progress
* Completed

Documentation:
* Test case1 documents

**Comment by Termiux** [comment]
For the time being I think the creation of a TestCase class and adding a Test Case property to ChangeOrder should at the very least help with some of the missing data we have right now for Test Case of every CO

**Comment by Termiux** [comment]
Commit b640dc580f493520103e224d078681b1bc866b8e already added a TestCase property based on the TestCase class already created a few commits back.
Most properties mentioned here are already supported but not all.
This functionality is still under development

**Comment by Termiux** [comment]
Commit 20af6443439bd995bb9be096643e349d07cf8701 added further functionality to support TestCases along with ChangeOrders. Subsequente changes have fixed bugs made by the changes

**Comment by Termiux** [comment]
The features introduced with 20af644 are working properly and the information related to the Test Cases can be seen in the local database file.

We need a proper UI to interact in  some way with that information already present

**Comment by Termiux** [comment]
We finally have proper TestCase support with the introducuction of the PwbObject_Summary form in e84648311cf23fb5edf0165b26b9ff8ae83940e6
